export const OPEN_STREET_MAP_API = `https://nominatim.openstreetmap.org/search`;
export const TILEMAP_LIGHT = `https://{s}.basemaps.cartocdn.com/rastertiles/voyager_nolabels/{z}/{x}/{y}{r}.png`;
export const TILEMAP_LIGHT_ATTRIBUTION = `&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors &copy; <a href="https://carto.com/attributions">CARTO</a>`;
export const TILEMAP_DARK = `https://{s}.basemaps.cartocdn.com/dark_nolabels/{z}/{x}/{y}{r}.png`;
export const TILEMAP_DARK_ATTRIBUTION = `&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors &copy; <a href="https://carto.com/attributions">CARTO</a>`;
export const TILEMAP_SUBDOMAINS = `abcd`;

export const COUNTRIES_ALL = [
  "United Arab Emirates",
  "Afghanistan",
  "Antigua and Barbuda",
  "Anguilla",
  "Albania",
  "Armenia",
  "Angola",
  // "Antarctica",
  "Argentina",
  "American Samoa",
  "Austria",
  "Australia",
  "Aruba",
  "Aland Islands",
  "Azerbaijan",
  "Bosnia and Herzegovina",
  "Barbados",
  "Bangladesh",
  "Belgium",
  "Burkina Faso",
  "Bulgaria",
  "Bahrain",
  "Burundi",
  "Benin",
  // "Saint-Barthélemy",
  "Bermuda",
  "Brunei Darussalam",
  "Bolivia",
  "Caribbean Netherlands",
  "Brazil",
  "Bahamas",
  "Bhutan",
  "Bouvet Island",
  "Botswana",
  "Belarus",
  "Belize",
  "Canada",
  // "Cocos Islands",
  "Democratic Republic of the Congo",
  "Centrafrican Republic",
  "Republic of the Congo",
  "Switzerland",
  // "Côte d'Ivoire",
  "Cook Islands",
  "Chile",
  "Cameroon",
  "China",
  "Colombia",
  "Costa Rica",
  "Cuba",
  "Cabo Verde",
  // "Curaçao",
  "Christmas Island",
  "Cyprus",
  "Czech Republic",
  "Germany",
  "Djibouti",
  "Denmark",
  "Dominica",
  "Dominican Republic",
  "Algeria",
  "Ecuador",
  "Estonia",
  "Egypt",
  "Western Sahara",
  "Eritrea",
  "Spain",
  "Ethiopia",
  "Finland",
  "Fiji",
  "Falkland Islands",
  "Federated states of Micronesia",
  "Faroe Islands",
  "France",
  "Gabon",
  "United Kingdom",
  "Grenada",
  "Georgia",
  "French Guiana",
  "Guernsey",
  "Ghana",
  "Gibraltar",
  "Greenland",
  "The Gambia",
  "Guinea",
  "Guadeloupe",
  "Equatorial Guinea",
  "Greece",
  "South Georgia and the South Sandwich Islands",
  "Guatemala",
  // "Guam",
  "Guinea Bissau",
  "Guyana",
  // "Heard Island and McDonald Islands",
  "Honduras",
  "Croatia",
  "Haiti",
  "Hungary",
  "Indonesia",
  "Ireland",
  "Israel",
  "Isle of Man",
  "India",
  "British Indian Ocean Territory",
  "Iraq",
  "Iran",
  "Iceland",
  "Italy",
  "Jersey",
  "Jamaica",
  "Jordan",
  "Japan",
  "Kenya",
  "Kyrgyzstan",
  "Cambodia",
  "Kiribati",
  "Comores",
  "Saint Kitts and Nevis",
  "North Korea",
  "South Korea",
  "Kuwait",
  "Cayman Islands",
  "Kazakhstan",
  "Laos",
  "Lebanon",
  "Saint Lucia",
  "Liechtenstein",
  "Sri Lanka",
  "Liberia",
  "Lesotho",
  "Lithuania",
  "Luxembourg",
  "Latvia",
  "Libya",
  "Morocco",
  "Monaco",
  "Moldova",
  "Montenegro",
  // "Saint Martin",
  "Madagascar",
  "Marshall Islands",
  "North Macedonia",
  "Mali",
  "Myanmar",
  "Mongolia",
  // "Macao",
  "Northern Mariana Islands",
  "Martinique",
  "Mauritania",
  "Montserrat",
  "Malta",
  "Mauritius",
  "Maldives",
  "Malawi",
  "Mexico",
  "Malaysia",
  "Mozambique",
  "Namibia",
  // "New Caledonia",
  "Niger",
  // "Norfolk Island",
  "Nigeria",
  "Nicaragua",
  "The Netherlands",
  "Norway",
  "Nepal",
  "Nauru",
  "Niue",
  "New Zealand",
  "Oman",
  "Panama",
  "Peru",
  "French Polynesia",
  "Papua New Guinea",
  "Philippines",
  "Pakistan",
  "Poland",
  "Saint Pierre and Miquelon",
  "Pitcairn",
  // "Puerto Rico",
  "Palestinian Territory",
  "Portugal",
  "Palau",
  "Paraguay",
  "Qatar",
  "Reunion",
  "Romania",
  "Serbia",
  "Russia",
  "Rwanda",
  "Saudi Arabia",
  "Solomon Islands",
  "Seychelles",
  "Sudan",
  "Sweden",
  "Singapore",
  "Saint Helena",
  "Slovenia",
  "Svalbard and Jan Mayen",
  "Slovakia",
  "Sierra Leone",
  "San Marino",
  // "Sénégal",
  "Somalia",
  "Suriname",
  // "São Tomé and Príncipe",
  "South Sudan",
  "El Salvador",
  "Saint Martin",
  "Syria",
  "eSwatini",
  "Turks and Caicos Islands",
  "Chad",
  // "French Southern and Antarctic Lands",
  "Togo",
  "Thailand",
  "Tajikistan",
  "Tokelau",
  "Timor-Leste",
  "Turkmenistan",
  "Tunisia",
  "Tonga",
  "Turkey",
  "Trinidad and Tobago",
  "Tuvalu",
  "Taiwan",
  "Tanzania",
  //"Ukraine", doesn't work for some reason
  "Uganda",
  // "United States Minor Outlying Islands",
  "United States of America",
  "Uruguay",
  "Uzbekistan",
  // "City of the Vatican",
  "Saint Vincent and the Grenadines",
  "Venezuela",
  "British Virgin Islands",
  "United States Virgin Islands",
  "Vietnam",
  "Vanuatu",
  "Wallis and Futuna",
  "Samoa",
  "Kosovo",
  "Yemen",
  "Mayotte",
  "South Africa",
  "Zambia",
  "Zimbabwe",
];
export const COUNTRIES_EASY = [
  "United Arab Emirates",
  "Afghanistan",
  "Austria",
  "Australia",
  "Bangladesh",
  "Belgium",
  "Brazil",
  "Canada",
  "Switzerland",
  "Chile",
  "China",
  "Germany",
  "Denmark",
  "Egypt",
  "Spain",
  "Ethiopia",
  "Finland",
  "Fiji",
  "France",
  "United Kingdom",
  "Greece",
  "Indonesia",
  "Ireland",
  "Israel",
  "India",
  "Iraq",
  "Iran",
  "Iceland",
  "Italy",
  "Japan",
  "North Korea",
  "South Korea",
  "Sri Lanka",
  "Madagascar",
  "Mongolia",
  "Mexico",
  "Malaysia",
  "The Netherlands",
  "Norway",
  "Nepal",
  "New Zealand",
  "Papua New Guinea",
  "Philippines",
  "Pakistan",
  "Poland",
  "Portugal",
  "Russia",
  "Rwanda",
  "Saudi Arabia",
  "Sweden",
  "Singapore",
  "Somalia",
  "Thailand",
  "Turkey",
  "Taiwan",
  //"Ukraine", doesn't work for some reason
  "United States of America",
  "Vietnam",
  "South Africa",
];

export const GLOBES = ["americas", "africa", "asia", "europe", "oceania"];
